// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'light-orange', 'dark-orange', 'light-green', 'dark-green', 'light-rose', 'dark-rose', 'light-violet', 'dark-violet']
    }
}

export {}
